services:
  stable-diffusion-webui:
#    user: "1000:1000"
    container_name: stable-diffusion-webui
#    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    image: sucicada/cuda-12.2.0-base-ubuntu22.04-runtime
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /home/peng/miniconda3:/home/peng/miniconda3:ro
      - ./entrypoint.sh:/entrypoint.sh
      - ../../:/app/
    command: make run
    ports:
      - "17860:17860"
    entrypoint: /entrypoint.sh
#    command: my_main_command --option1 value1
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
